version: 1.0.{build}
environment:
  matrix:
  - PYTHON: C:\\Python27
  - PYTHON: C:\\Python27-x64
  - PYTHON: C:\\Python33
  - PYTHON: C:\\Python33-x64
    DISTUTILS_USE_SDK: 1
  - PYTHON: C:\\Python34
  - PYTHON: C:\\Python34-x64
    DISTUTILS_USE_SDK: 1
  - PYTHON: C:\\Python35
  - PYTHON: C:\\Python35-x64
  - PYTHON: C:\\Python36
  - PYTHON: C:\\Python36-x64
  - PYTHON: C:\\Python37
  - PYTHON: C:\\Python37-x64
  - PYTHON: C:\\Python38
  - PYTHON: C:\\Python38-x64
  - image: Visual Studio 2019
    PYTHON: C:\\Python39
  - image: Visual Studio 2019
    PYTHON: C:\\Python39-x64
install:
- ps: >-
    # We need wheel installed to build wheels

    & $env:PYTHON\python.exe -m pip install wheel


    # Add wrapper script

    @'

    @echo off

    :: To build extensions for 64 bit Python 3, we need to configure environment

    :: variables to use the MSVC 2010 C++ compilers from GRMSDKX_EN_DVD.iso of:

    :: MS Windows SDK for Windows 7 and .NET Framework 4

    ::

    :: More details at:

    :: https://github.com/cython/cython/wiki/64BitCythonExtensionsOnWindows


    IF "%DISTUTILS_USE_SDK%"=="1" (
        ECHO Configuring environment to build with MSVC on a 64bit architecture
        ECHO Using Windows SDK 7.1
        "C:\Program Files\Microsoft SDKs\Windows\v7.1\Setup\WindowsSdkVer.exe" -q -version:v7.1
        CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release
        SET MSSdk=1
        REM Need the following to allow tox to see the SDK compiler
        SET TOX_TESTENV_PASSENV=DISTUTILS_USE_SDK MSSdk INCLUDE LIB
    ) ELSE (
        ECHO Using default MSVC build environment
    )


    CALL %*

    '@ | out-file -encoding ASCII build.cmd
build_script:
- cmd: build.cmd %PYTHON%\\python.exe setup.py bdist_wheel
test: off
artifacts:
- path: dist\*
deploy: off
notifications:
- provider: Email
  to:
  - bgilbert@backtick.net
  - jaharkes@cs.cmu.edu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
